[package]
name = "libp2p-bitswap-next"
version = "0.26.2"
authors = ["Darius C", "David Craven <david@craven.ch>"]
edition = "2018"
description = "Implementation of the ipfs bitswap protocol."
license = "MIT OR Apache-2.0"
repository = "https://github.com/dariusc93/rust-ipfs"

[features]
default = []
compat = ["quick-protobuf", "quick-protobuf-codec", "asynchronous-codec"]

[dependencies]
async-trait = "0.1.74"
fnv = "1.0.7"
futures = "0.3.29"
lazy_static = "1.4.0"
libipld = { version = "0.16.0", default-features = false }
libp2p = { version = "0.53", features = ["request-response"] }
prometheus = "0.13.0"
thiserror = "1.0.57"
tracing = "0.1.40"
unsigned-varint = { version = "0.8.0", features = ["futures", "asynchronous_codec"] }
quick-protobuf = { version = "0.8.1", optional = true }
quick-protobuf-codec = { version = "0.3", optional = true }
asynchronous-codec = { version = "0.7", optional = true }
bytes = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.14", features = ["js"] }

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
env_logger = "0.10.2"
libipld = { version = "0.16.0", default-features = false, features = ["dag-cbor"] }
libp2p = { version = "0.53", features = ["tcp", "noise", "yamux", "rsa", "ed25519", "async-std"] }
multihash = { version = "0.18.0", default-features = false, features = ["blake3", "sha2"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter","tracing-log"] }
