[package]
name = "rust-ipns"
rust-version = "1.70"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/dariusc93/rust-ipfs"
description = "Rust implementation of IPNS"
version = "0.4.0"
authors = ["Darius Clark"]
keywords = ["libp2p", "ipfs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbor4ii = { version = "0.3", features = ["serde1"] }
quick-protobuf = "0.8"
cid = "0.11"
serde = { version = "1", features = ["derive"] }
multihash = { version = "0.18" }
sha2 = { version = "0.10" }
chrono = { version = "0.4" }

libp2p-identity = { version = "0.2", optional = true, features = [
    "ecdsa",
    "ed25519",
    "peerid",
    "rand",
    "rsa",
    "secp256k1",
] }
derive_more = "0.99"

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }

[features]
default = ["libp2p"]
libp2p = ["dep:libp2p-identity"]
